const crypto = require('crypto');

let password = '123@';
var shasum = crypto.createHash('sha1');
let salt = 'random string';
shasum.update(password + salt);
password = shasum.digest('hex');

module.exports = {
  Fake_User: [
    [
      '손흥민',
      password,
      28,
      '서울',
      'https://www.sporbiz.co.kr/news/photo/201907/353469_263513_1945.jpg',
      '소농민',
      'O',
      '남자',
      '가끔',
      '전혀안함',
      '축구선수',
      '고등학교',
    ],
    [
      '박서준',
      password,
      31,
      '서울',
      'https://t1.daumcdn.net/cfile/tistory/99A175355AA7355232',
      '존잘 박서준',
      'A',
      '남자',
      '피할 수 없을때만',
      '전혀안함',
      '배우',
      '대학교 졸업',
    ],
    [
      '김세정',
      password,
      23,
      '서울',
      'https://img.insight.co.kr/static1/2019/04/25/700/s3159ono4qt6a8a6obfr.jpg',
      '존예 김세정',
      'AB',
      '여자',
      '자주',
      '전혀안함',
      '가수',
      '고등학교 졸업',
    ],
    [
      '강동원',
      password,
      39,
      '인천',
      'https://file.mk.co.kr/meet/neds/2018/02/image_readtop_2018_103482_15184980633205018.jpg',
      '존잘 강동원',
      'O',
      '남자',
      '자주',
      '가끔',
      '배우',
      '대학교 졸업',
    ],
    [
      '문채원',
      password,
      33,
      '인천',
      'https://www.mediapia.co.kr/news/photo/201908/2_43998_59255_2613.jpg',
      '존예보스 문채원',
      'AB',
      '여자',
      '가끔',
      '전혀안함',
      '배우',
      '대학교 졸업',
    ],
    [
      '박보영',
      password,
      30,
      '서울',
      'https://img.segye.com/content/image/2020/01/04/20200104502674.jpg',
      '뽀블리',
      'A',
      '여자',
      '자주',
      '전혀안함',
      '배우',
      '대학교 졸업',
    ],
    [
      '박보검',
      password,
      27,
      '인천',
      'https://img.khan.co.kr/lady/201602/20160229170513_1_qhrja1.jpg',
      '보검신',
      'B',
      '남자',
      '전혀안함',
      '전혀안함',
      '배우',
      '대학교 졸업',
    ],
    [
      '지효',
      password,
      23,
      '인천',
      'https://www.mbcsportsplus.com/data/board/attach/2019/08/20190802091458_zsbaiyqn.jpg',
      '트와이스 지효',
      'B',
      '여자',
      '가끔',
      '전혀안함',
      '가수',
      '고등학교 졸업',
    ],
    [
      '여진구',
      password,
      22,
      '서울',
      'https://lh3.googleusercontent.com/proxy/rm1vvuMgH1UCxC5mMgJqNwj8jHgoJd3NO--XeTo9p2uM-EIJL7Eblc-wRiAA2QnnRpi1k5PQx0N7YUU7AkYz9xquWhFybrxdVAci2O0S_B89orggktZLvnH7',
      '진구형',
      'AB',
      '남자',
      '자주',
      '자주',
      '배우',
      '고등학교 졸업',
    ],
    [
      '다현',
      password,
      22,
      '인천',
      'https://1.bp.blogspot.com/-1pTlOSO9NX0/Xn88LB61tmI/AAAAAAAADaY/U49-b7YjVo41yeuunCQvMctDhFWb3wqrwCLcBGAsYHQ/s1600/0b9463d3b6a6c873f6f8dd904627426e.jpg',
      '트와이스 다현',
      'O',
      '여자',
      '가끔',
      '전혀안함',
      '가수',
      '고등학교 졸업',
    ],
    [
      '송중기',
      password,
      34,
      '인천',
      'https://monthly.chosun.com/up_fd/Mdaily/2019-06/bimg_thumb/%EC%86%A1%EC%A4%91%EA%B8%B02222.jpg',
      '존잘 손중기',
      'AB',
      '남자',
      '자주',
      '전혀안함',
      '배우',
      '대학교 졸업',
    ],
    [
      '김지원',
      password,
      29,
      '서울',
      'https://www.nbnnews.co.kr/news/photo/201909/322891_370889_190.jpg',
      '존예보스 김지원',
      'B',
      '여자',
      '가끔',
      '전혀안함',
      '배우',
      '대학교 졸업',
    ],
    [
      '손예진',
      password,
      38,
      '서울',
      'https://img.huffingtonpost.com/asset/5e2e89a52400002d0664c5f0.jpeg?cache=QYmkLa6rZc&ops=scalefit_630_noupscale',
      '밥 잘 사주는 예쁜 누나',
      'O',
      '여자',
      '자주',
      '전혀안함',
      '배우',
      '대학교 졸업',
    ],
    [
      '송하윤',
      password,
      33,
      '서울',
      'https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Ft1.daumcdn.net%2Fcfile%2Ftistory%2F998436485B9F6C3D17',
      '여신 송하윤',
      'O',
      '여자',
      '가끔',
      '전혀안함',
      '배우',
      '대학교 졸업',
    ],
    [
      '한효주',
      password,
      33,
      '서울',
      'https://img8.yna.co.kr/photo/cms/2018/07/27/01/C0A8CAE200000164D92FA2B20000302C_P2.jpg',
      '여신 한효주',
      'AB',
      '여자',
      '자주',
      '전혀안함',
      '배우',
      '대학교 졸업',
    ],
    [
      '김태리',
      password,
      30,
      '서울',
      'https://img.newspim.com/magazine/2018/03/201803_86f167b8cf.jpg',
      '연기왕 김태리',
      'B',
      '여자',
      '가끔',
      '전혀안함',
      '배우',
      '대학교 졸업',
    ],
    [
      '공유',
      password,
      40,
      '서울',
      'https://topclass.chosun.com/news_img/1912/1912_058.jpg',
      '젠틀 공유',
      'O',
      '남자',
      '자주',
      '전혀안함',
      '배우',
      '대학교 졸업',
    ],
    [
      '김수현',
      password,
      32,
      '서울',
      'https://dimg.donga.com/wps/NEWS/IMAGE/2020/02/07/99580154.2.jpg',
      '수현짱',
      'AB',
      '남자',
      '가끔',
      '가끔',
      '배우',
      '대학교 졸업',
    ],
  ],
};
